---
- name: Install and confiugure traefik
  gather_facts: false
  hosts: traefik
  tasks:

    - name: Add the user 'traefik'
      become: yes
      ansible.builtin.user:
        create_home: no
        name: traefik

    - name: Download and unarchive traefik binary
      become: yes
      ansible.builtin.unarchive:
        src: https://github.com/traefik/traefik/releases/download/v2.4.13/traefik_v2.4.13_linux_amd64.tar.gz
        dest: /usr/local/bin
        creates: /usr/local/bin/traefik
        exclude:
          - "*.md"
        owner: traefik
        remote_src: yes

    - name: Ensure config directory exists
      become: yes
      ansible.builtin.file:
        path: /etc/traefik
        state: directory

    - name: Copy traefik config
      become: yes
      ansible.builtin.copy:
        src: ./files/traefik.toml
        dest: /etc/traefik/traefik.toml
        owner: root
        group: root
        mode: 0644

    - name: Create traefik systemd unit
      become: yes
      ansible.builtin.copy:
        src: ./files/traefik.service
        dest: /etc/systemd/system/traefik.service
        owner: root
        group: root
        mode: 0644

    - name: Ensure traefik service is enabled and running
      become: yes
      ansible.builtin.systemd:
        name: traefik
        state: restarted
        enabled: yes
        daemon_reload: yes