apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: external-dns

namespace: external-dns

resources:
  - namespace.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - service-account.yaml
  - deployment.yaml
