---
http:
  routers:
    authelia:
      rule: "Host(`auth.monke.science`)"
      service: authelia@file
      tls:
        certResolver: dns

    traefik:
      rule: "Host(`traefik.monke.science`)"
      middlewares:
        - authelia@file
      service: api@internal
      tls:
        certResolver: dns

    heimdall:
      rule: "Host(`heimdall.monke.science`) || Host(`monke.science`)"
      middlewares:
        - authelia@file
      service: heimdall@file
      tls:
        certResolver: dns
    
    proxmox:
      rule: "Host(`proxmox.monke.science`)"
      middlewares:
        - authelia@file
      service: proxmox@file
      tls:
        certResolver: dns


  middlewares:
    authelia:
      forwardauth:
        address: "http://authelia:9091/api/verify?rd=https://auth.monke.science/"
        trustForwardHeader: true
        authResponseHeaders: 
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Name"
          - "Remote-Email"
        tls:
          insecureSkipVerify: true


  services:
    authelia:
      loadBalancer:
        servers:
        - url: "http://authelia:9091/"

    heimdall:
      loadBalancer:
        servers:
        - url: "https://192.168.134.105/"

    proxmox:
      loadBalancer:
        servers:
        - url: "https://192.168.134.90:8006/"


udp:
  routers:
    wireguard:
      service: wireguard@file
      entryPoints:
        - "vpn"
      
  services:
    wireguard:
      loadBalancer:
        servers:
        - address: "192.168.134.102:51820"