apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: homer-config-map
      containers:
        - name: homer
          image: b4bz/homer:v22.11.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /www/assets/config.yml
              subPath: config.yml
