apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: homer

namespace: homer

configMapGenerator:
  - name: homer-config-map
    files:
      - config.yml

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml