---
- name: Install haproxy
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Copy haproxy configuration
  ansible.builtin.template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy
