---
version: "3.3"

services:

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes: 
      - /etc/reverse-proxy/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /etc/reverse-proxy/traefik/acme.json:/acme.json:rw
      - /etc/reverse-proxy/traefik/traefik_dynamic.yaml:/etc/traefik/traefik_dynamic.yaml:ro
    environment: 
     - TZ=Europe/Berlin
     - NAMECHEAP_API_USER
     - NAMECHEAP_API_KEY

  authelia:
    image: authelia/authelia:4
    container_name: authelia
    volumes:
      - /etc/reverse-proxy/authelia:/config
    expose:
      - 9091
    restart: always
    healthcheck:
      disable: true
    environment:
      - TZ=Europe/Berlin
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD
      - AUTHELIA_JWT_SECRET
