version: '3.8'

services:
  grafana:
    restart: always
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "{{ admin_user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ admin_password }}"
    volumes:
      - grafana_data:/var/lib/grafana:rw
      - ./grafana:/etc/grafana/provisioning/:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]

  prometheus:
    user: root
    restart: always
    image: prom/prometheus:v2.46.0
    container_name: prometheus
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus/data/:rw
      - ./prometheus/prometheus.yaml:/prometheus/prometheus.yml:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090" ]

volumes:
  grafana_data:
  prometheus_data: