apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-persistent-volume-claim
  namespace: jenkins
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
