apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-persistent-volume
  namespace: jenkins
spec:
  storageClassName: local-path
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/jenkins"
