###############################################################
#                   Kubernetes variables                      #
###############################################################
k3s_load_balancer_ip: "{{ hostvars[groups['k3s_load_balancer'][0]]['ansible_default_ipv4'].address }}"
k3s_port: 6443
k3s_url: "https://{{ k3s_load_balancer_ip }}:{{ k3s_port }}"
k3s_clean_install: true
