---
kubernetes_version: 1.22.2
kubernetes_apt_version: "{{ kubernetes_version }}-00"
kubernetes_kubeadm_version: "v{{ kubernetes_version }}"
kubernetes_master_ip: "{{ hostvars[groups['k8s_master'][0]]['ansible_default_ipv4'].address }}"
kubernetes_cidr: 10.244.0.0/16
