---
- name: Install k3s-load-balancer
  hosts: k3s_load_balancer
  become: yes
  vars_files:
    - vars/kubernetes.defaults.yaml
    - vars/secrets.yaml
  roles:
    - k3s/load-balancer

- name: Install k3s-master
  hosts: k3s_master
  become: yes
  vars_files:
    - vars/kubernetes.defaults.yaml
    - vars/secrets.yaml
  roles:
    - k3s/master

- name: Install k3s-master-join
  hosts: k3s_master_join
  become: yes
  vars_files:
    - vars/kubernetes.defaults.yaml
    - vars/secrets.yaml
  roles:
    - k3s/master-join

- name: Install k3s-worker
  hosts: k3s_worker
  become: yes
  vars_files:
    - vars/kubernetes.defaults.yaml
    - vars/secrets.yaml
  roles:
    - k3s/worker
