---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: letsencrypt
spec:
  acme:
    # Email address used for ACME registration
    email: allround.email@gmail.com
    # The ACME server URL
    # Staging:    https://acme-staging-v02.api.letsencrypt.org/directory
    # Production: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    # Name of the secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # Enable the HTTP-01 challenge provider using traefik
    solvers:
      - http01:
          ingress:
            ingressTemplate:
              metadata:
                annotations:
                  kubernetes.io/ingress.class: traefik
