---
- name: Reset Kubernetes component
  shell: "kubeadm reset --force"

- name: Join the Kubernetes cluster
  shell: |
    kubeadm join --token {{ kubernetes_token }} \
                --discovery-token-unsafe-skip-ca-verification \
                {{ kubernetes_master_ip }}:6443

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
