---
- name: Enable ip forwarding
  become: yes
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes

- name: Install wireguard
  become: yes
  ansible.builtin.apt:
    name: wireguard
    state: present

- name: Create wireguard server config
  become: yes
  ansible.builtin.template:
    dest: /etc/wireguard/wg0.conf
    src: wg0.conf
    owner: root
    group: root
    mode: 0600
  notify: Restart wireguard

- name: Start wireguard and enable on boot
  become: yes
  ansible.builtin.systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started