---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Delete old forwards
  ansible.builtin.file:
    state: absent
    path: /etc/nginx/sites-enabled

- name: Create forwards
  ansible.builtin.copy:
    dest: /etc/nginx/
    src: sites-enabled
    mode: '644'
  notify: Restart nginx

- name: Create nginx server config
  ansible.builtin.template:
    dest: /etc/nginx/nginx.conf
    src: nginx.conf
    mode: '644'
  notify: Restart nginx

# certbot revoke --cert-name example.com
- name: Creates tls certificates
  loop:
    - monke.science
    - grafana.dojo.monke.science
  ansible.builtin.command: certbot --non-interactive --nginx -d {{ item }}
  args:
    creates: /etc/letsencrypt/live/{{ item }}/cert.pem
  notify: Restart nginx