---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Disable the default site
  file:
    path:  /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Create monke.science
  ansible.builtin.template:
    dest: /etc/nginx/sites-enabled/monke.science
    src: monke.science
    mode: '644'
  notify: Restart nginx

- name: Create nginx server config
  ansible.builtin.template:
    dest: /etc/nginx/nginx.conf
    src: nginx.conf
    mode: '644'
  notify: Restart nginx