---  
- name: Install docker
  ansible.builtin.apt:
    name: docker.io
    state: present

- name: Ensure group docker exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add the user {{ ansible_user }} to the docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install docker-compose
  ansible.builtin.apt:
    name: docker-compose
    state: present