---
- name: Install k8s-masters
  hosts: k8s_master
  become: yes
  vars_files:
    - vars/defaults.yaml
    - vars/secrets.yaml
  roles:
    - kubernetes/master

- name: Install k8s-nodes
  hosts: k8s_worker
  become: yes
  vars_files:
    - vars/defaults.yaml
    - vars/secrets.yaml
  roles:
    - kubernetes/worker