---
- name: Copy containerd configuration
  ansible.builtin.copy:
    src: containerd.conf
    dest: /etc/modules-load.d/containerd.conf

- name: Enable overlay, bridge-netfilter
  community.general.modprobe:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: 'overlay' }
    - { name: 'br_netfilter' }

- name: Setup required sysctl params
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }

- name: Install containerd
  ansible.builtin.apt:
    name: containerd
    state: present

- name: Add Google Cloud public signing key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: Install kubernetes packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    update_cache: yes
    state: present
  with_items:
  - { name: "kubelet={{ kubernetes_apt_version}}" }
  - { name: "kubeadm={{ kubernetes_apt_version}}" }
  - { name: "kubectl={{ kubernetes_apt_version}}" }
