---
- name: Check if rke2-uninstall.sh exists
  stat:
    path: /usr/local/bin/rke2-uninstall.sh
  register: uninstall_rke2

- name: Uninstall rke2 master node
  command:
    cmd: sh rke2-uninstall.sh
    chdir: /usr/local/bin
  when: uninstall_rke2.stat.exists